### ISSUE TITLE
#187 2. Création de la liste des images à valider

### ISSUE THREAD

**Issue by alexandregranier** [telabotanica/obs-saisons.fr#189]
Par l’intermédiaire du menu "modérer les images",
on arrive sur la liste qui n'ont pas été traités.
Elles sont en miniatures, et cliquable.
Elles sont présenés avec le nom de la station, de l'utilisateur et la date du jour.
Classées par les plus vielles en premier.

**Comment by Funloi2** [comment]
Ticket terminet
![List images 1](https://github.com/telabotanica/obs-saisons.fr/assets/102960932/ba338974-7726-4f41-bb0b-dc14a4d1772e)
