### ISSUE TITLE
#187 3. Permettre la validation

### ISSUE THREAD

**Issue by alexandregranier** [telabotanica/obs-saisons.fr#190]
Contexte:
suite à l'ajout d'une image sur l'application par un utilisateur.
Sur l'espace "modérer une image" l'admin voit toutes images
non validées sous forme de miniature.
Les images apparaissent dans un carroussel, qui permet de les parcourir.
Un bouton radio  ou un et checkbox dans une liste,
sur un clic on arrive à l'étape de validation. -> oui / non
si non -> motif à sasir -> email

BD : ajouter un champs dans la table "observation" indquant si l'image est valide ou non.
-> par défaut "invalide". -> format 0 ou 1.

**Comment by Funloi2** [comment]
Ticket terminé.
![Uploading Verification image.PNG…]()
