### ISSUE TITLE
Ajouter du style sur la page d'administration des images

### ISSUE THREAD

**Issue by Julianomatt77** [telabotanica/obs-saisons.fr#200]
1. Ajouter du style

![Capture d’écran du 2024-04-17 09-05-12](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/e7a4e5a0-681e-46e1-8cfa-aadcbbe36b2d)

Voir la page résultats pour les select.

Bouton filtrer -> bouton vert avec les même propriétés que les autres boutons du site 'class bt + bt-add par exemple.

Rajouter de l'espace entre le bouton filtrer et le tableau

2. Ajouter une colonne avec la date des photos.

3. Pouvoir trier les photos par date

**Comment by Funloi2** [comment]
J'ai mis à jour les filtres.
Le filtre par date, tu veux un de façons à trier que par date sélectionner? de trier que pour les dates avant la date sélectionné ou juste de pouvoir choisir entre les photos les plus récentes en premier?

**Comment by Julianomatt77** [comment]
Juste pouvoir sélectionner de la + récente à la plus vieille et vice-versa

**Comment by Julianomatt77** [comment]
Non c'est bon comme ça.

**Comment by Julianomatt77** [comment]
merged sur la branch develop
