### ISSUE TITLE
Carousel sur page espèce

### ISSUE THREAD

**Issue by Julianomatt77** [telabotanica/obs-saisons.fr#202]
Le carousel ne s'affiche pas.
$images est vide -> problème avec la requête sql

Capture d'ecran de dd($images):
![Capture d’écran du 2024-04-17 09-21-30](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/fe6cf68c-33ec-406a-a28d-691395d9d2af)

**Comment by Julianomatt77** [comment]
Non j'ai pris ton dernier commit et fait la migration doctrine. 
Les images sont bien présentes dans la station mais ne sont pas récupérés lors de tes appels à la bdd que ce soit pour le carousel ou pour la modération d'images admin.

**Comment by Funloi2** [comment]
j'ai modifié le code pour les 2, tu peux vérifier et me tenir au courant?

**Comment by Julianomatt77** [comment]
est-ce que tu as bien push?

Je vois commit il y a 26 min avec des modifs sur le speciesController -> Ca ne s'affiche toujours pas et pas de modif push sur l'admincontroller

**Comment by Funloi2** [comment]
Oui, j'ai push sur la branche feat/carousel, c'est dessus qu'il y a tous, j'ai changé le src afin que ca fonctionne.

ancien : 
src="{{ image.picture }}"

nouveau : 
src="{{ asset(image.picture) }}"

**Comment by Julianomatt77** [comment]
Bon ok le carousel ne s'affichait pas parceque je n'avais pas d'image validées donc ça c'est ok.

Par contre les images ne s'affichent toujours pas. Il faut que tu supprime le asset que tu as rajouté -> ca fait buger

![Capture d’écran du 2024-04-17 10-19-10](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/93618b89-2a59-4d18-8e6b-52d23642def6)

Sans le asset tu as toujours un problème d'image:
![Capture d’écran du 2024-04-17 10-19-38](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/d7616b8d-15d4-4bac-8f61-e4eea1f1931c)

Dans le speciesController supprime ta 2eme ligne $species (ligne 76) , c'est un doublon avec la ligne 69
![Capture d’écran du 2024-04-17 10-20-19](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/7f642d70-af6c-4f3d-9f3a-6059e90b4918)

**Comment by Funloi2** [comment]
J'ai fait les changements, j'ai enlevé le doublons de la ligne 76. Mais on dirait que le problèmes d'image vide est que la fonction findImagesCarousel n'est pas trouvé dans ton ObservationRepository. Tu pourrais vérifier?

**Comment by Julianomatt77** [comment]
Tu peux remettre le asset, ce n'est pas ça qui gênait.

Le problème vient du fait qu'il n'y a pas toujours de photo.

1. Admin
Quand il n'y a pas de photo ou que l'url de la photo commence par /media il ne faut pas afficher de ligne car il n'y a pas de photo à modérer
![Capture d’écran du 2024-04-17 11-08-28](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/3811822e-4a93-4375-accc-a0e06686cb97)

2.Carousel
Là encore il ne faut afficher les images que si la valeure n'est pas nulle sinon -> bug.

3.Carousel
S'il n'y a aucune image utilisateur pour l'espèce en question (ou s'il y en a moins que 3 par exemple) -> aller prendre les images par défaut dans /media/species (dans la table species le nom du début des images par défault est inscris dans la colonne picture donc par exemple tu affiche toutes les photos du répertoire qui commence par species.picture)

**Comment by Funloi2** [comment]
j'ai effectué les modifications. Je me demandais si quand il n'y a pas d'image, on n'affiche juste pas le carrousel? car sinon ça devient un doublons des images qui sont déjà présent dans la publications

**Comment by Julianomatt77** [comment]
Non, le but c'est de remplacer les images de la fiche par le carousel.

Par contre quand un utilisateur remplace une image déjà validée, elle reste validée. Il faudrait qu'elle repasse en "a vérifier".

**Comment by Funloi2** [comment]
J'ai éffectué les changements, j'ai juste pas pu les testé car dans ma bdd, la valeur de 'picture' dans la table 'species' est la même que le vernacular name

**Comment by Funloi2** [comment]
Ou se trouve la partie édité d'une observation? je cherche la requête ou son affichage mais je ne trouve pas.

**Comment by Julianomatt77** [comment]
Dans ta staion, tu as une liste d'individus que tu as sélectionné et quand tu clique dessus un calendrier s'ouvre avec tes observations. Quand tu clique sur une observation tu peux ensuite cliquer sur modifier à droite.

![Capture d’écran du 2024-04-18 14-30-52](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/1a5ab373-81ec-431e-ba70-9fb18c3f9c9d)

![Capture d’écran du 2024-04-18 14-31-14](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/30fa2930-25f4-4bc6-b4c3-d89f5fbc2772)

**Comment by Funloi2** [comment]
Désolé je me suis mal exprimé, je voulais dire dans le code. J'ai trouvé un fichier JS qui pourrais y ressemblais mais si c'est ça, je ne vois pas comment faire la modification depuis ce fichier. Il s'agit de Observation-overlay.js .

**Comment by Julianomatt77** [comment]
C'est dans le StationController, quand l'image d'une obs est remplacée il faut juste remettre la valeur de is_picture_valid à 0

**Comment by Funloi2** [comment]
Merci, l changement est effectué.

**Comment by Julianomatt77** [comment]
S'il n'y a pas d'observation il y a un mauvais chemin pour les photos du carousel:

![Capture d’écran du 2024-04-25 10-55-42](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/e7c246c3-2547-445e-b69e-9c7d61ba7eed)

**Comment by Julianomatt77** [comment]
Pour le nom affiché sur le carousel, afficher le display_name et pas le name (pour éviter de diffuser le vrai nom des personnes si celles-ci ne le veulent pas) et si pas de display_name mettre 'anonyme'

![Capture d’écran du 2024-04-25 15-27-16](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/e6f8d686-76c2-442b-8e03-37a56f55fb50)

**Comment by Julianomatt77** [comment]
Tout m'a l'air ok, je ferme
