### ISSUE TITLE
Mail lors du rejet d'une photo

### ISSUE THREAD

**Issue by Julianomatt77** [telabotanica/obs-saisons.fr#205]
Si une photo est rejeté par un admin, il faut envoyer un mail à l'utilisateur avec le motif.

La fonction d'envoi de mail est déjà écrite (service EmailSender, fonction send)

Tu as un exemple dans le UserController, fonction register.

Il faudra créer un nouveau template d'email.

**Comment by Funloi2** [comment]
J'ai ajouté le template du mail et l'envoie du mail.
C'est sur une nouvelle branche "feat/mail-refus_image".

**Comment by Julianomatt77** [comment]
1. Petites fautes d'orthographe sur le mail:

![Capture d’écran du 2024-04-25 09-50-01](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/1515fa13-54d6-42f6-ac27-ee21d90af02b)

Image refusée

Image envoyée refusée

2. Rajouter un paragraphe:

Si vous souhaitez que votre photo puisse être visible par la communauté, merci de la modifier.
Pour toute question n'hésitez pas à nous contacter: contact@obs-saisons.fr

**Comment by Funloi2** [comment]
J'ai apporté les modifications demandé.

**Comment by Julianomatt77** [comment]
Est-ce que tu peux rajouter un lien pour contact@obs-saisons.fr stp ?

**Comment by Julianomatt77** [comment]
![Capture d’écran du 2024-04-25 10-44-54](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/4dc7895e-1b06-48d0-a4b8-f3153d572775)

Il faut changer  'link' => $this->generateUrl('observation_edit', ['id' => $observation->getId()]), par :
'link' => $this->generateUrl('observation_edit', ['observationId' => $observation->getId()]),

(le parametre attendu pour la route observation_edit est observationId et pas id

**Comment by Julianomatt77** [comment]
Le lien généré pour l'observation ne marche pas, seules les paramètres sont générés:

![Capture d’écran du 2024-04-25 10-49-08](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/daf172ab-39ad-44f8-9ac3-b86c21fcd32b)

Il faut générer le lien absolu et pas seulement la route symfony.

**Comment by Julianomatt77** [comment]
Le lien ne marche toujours pas, en effet il n'y a pas d'url spécial pour l'edit d'une observation.

![Capture d’écran du 2024-05-15 09-06-18](https://github.com/telabotanica/obs-saisons.fr/assets/89195193/c91fd424-7795-4518-88f2-017300bba0d7)

Plutôt que de mettre ce lien vers l'observation mettre un lien vers la station et préciser sur quel individu + lien vers la photo en question. On aurait donc un mail du genre :

<p>Bonjour {{ user }},</p>
    Votre **<a href="{{ linkImage }}" target="_blank">**image**</a>** a été refusée par un modérateur pour la raison suivante : {{ motif }}
    <p>

**<p>Cette image appartient à la station <a>{{ stationName }}</a> et porte sur l'individu {{ IndividuName }}.</p>**
